// This file was autogenerated by generate-source-plugin.js

// includes
#include <cstddef>
#include <cstdint>
#include <WString.h>

/// compiled web asset
struct WebAsset {
  String          path;     ///< URL path (/index.html)
  const char*     mimeType; ///< associated mime type
  size_t          length;   ///< data length (in bytes)
  const uint8_t*  data;     ///< asset data
};

/// path comparison
struct WebAssetPathCompare {
    bool operator()(const String& lhs, const WebAsset& rhs) {
        return lhs < rhs.path;
    }
    bool operator()(const WebAsset& lhs, const String& rhs) {
        return lhs.path < rhs;
    }
};

extern const WebAsset webAssets[];  ///< array of compiled assets
extern const size_t webAssetsCount; ///< entries in array
